version: '2'
services:
  db:
    image: postgres:17
    user: root
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    restart: always             # run as a service
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$POSTGRES_PASSWORD psql --dbname=$POSTGRES_DB --username=$POSTGRES_USER -c 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
        - ./postgresql:/var/lib/postgresql/data
  odoo18setup:
    image: odoo:18
    user: root
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "$ODOO_PORT:8069"
      - "$ODOO_CHAT_PORT:8072" # live chat
    tty: true
    command: "$ODOO_INIT_CMD"
    environment:
      - HOST=db
      - USER=$POSTGRES_USER
      - PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: no 
  odoo18:
    image: odoo:18
    user: root
    depends_on:
      odoo18setup:
        condition: service_completed_successfully
    ports:
      - "$ODOO_PORT:8069"
      - "$ODOO_CHAT_PORT:8072" # live chat
    tty: true
    environment:
      - HOST=db
      - USER=$POSTGRES_USER
      - PASSWORD=$POSTGRES_PASSWORD
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    